export { PrismaClient, Prisma } from '@prisma/client';
export type {
  User,
  Address,
  Category,
  Product,
  ProductVariant,
  ProductImage,
  Favorite,
  Coupon,
  Cart,
  CartItem,
  Order,
  OrderItem,
  PaymentEvent,
  Review,
  InventoryMovement,
  Role,
  ProductStatus,
  ProductBadge,
  PaymentStatus,
  FulfillmentStatus,
  CouponType,
  ReviewStatus,
  InventoryReason,
} from '@prisma/client';
